

export const metadata = {
    title: 'Create Next only App',
    description: 'Generated by create next app',
}

export default function Layout({ children }) {
    return (

        <div>
            {children}
        </div>


    )
}